(function(){
  const PROFILE_KEY='mesacards_profile_v7';
  const $=s=>document.querySelector(s), esc=v=>String(v||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  function profile(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY))||{avatar:'👤'}}catch{return{avatar:'👤'}}}
  function head(title,sub,icon='🂡'){return `<div class="mc-game-head"><button class="mc-back" onclick="navHome()">‹</button><div class="mc-game-title">${icon} ${title}<br><small>${sub}</small></div><div class="mc-balance"><span class="mc-chip"></span>${state.players?.[0]?.chips||40}</div><button class="mc-menu" onclick="openSettings()">☰</button></div>`}
  function val21(cards){return bjValue(cards)}
  const oldBJ=window.renderBJ;
  window.renderBJ=renderBJ=function(){try{const g=state.data,h=g.hands[g.current],p=profile();app.innerHTML=`<main class="mc-game-screen">${head('21 Flash','Local · fichas virtuales','🂡')}<section class="mc-table"><div class="mc-dealer"><span class="mc-avatar">👩‍💼</span><h3>Banca</h3><div class="cards">${g.dealer.map((c,i)=>!g.done&&i===1?cardHTML(null,true):cardHTML(c,true)).join('')}</div><span class="mc-score">${g.done?val21(g.dealer):'?'}</span><p style="color:var(--mc-muted)">La banca debe plantarse en 17 o más</p></div><div class="mc-player-ring">${g.hands.map((hand,i)=>`<div class="mc-player-pill ${i===g.current&&!g.done?'active':''}"><b>${i===0?(p.avatar||'👤'):'👤'} ${esc(hand.name)}</b><div class="cards">${hand.cards.map(c=>cardHTML(c,true)).join('')}</div><small>${val21(hand.cards)} · ${esc(hand.result || (i===g.current?'Turno':'Esperando'))}</small></div>`).join('')}</div><div class="mc-my-hand"><h3>${esc(h.name)} <span class="mc-score">${val21(h.cards)}</span></h3><div class="cards">${h.cards.map(c=>cardHTML(c)).join('')}</div></div></section>${renderLog(g.log)}<div class="mc-action-dock">${g.done?`<button class="mc-btn primary" onclick="startBJ()">Nueva ronda</button><button class="mc-btn outline" onclick="navHome()">Salir</button>`:`<button class="mc-btn primary" onclick="bjHit()">🂠 Pedir</button><button class="mc-btn outline" onclick="bjStand()">✋ Plantarse</button>`}</div></main>`}catch(e){oldBJ?.()}};
  const oldHoldem=window.renderHoldem;
  window.renderHoldem=renderHoldem=function(){try{const g=state.data,p=profile();app.innerHTML=`<main class="mc-game-screen">${head('Hold’em Social',`${g.street} · local`,'♠')}<section class="mc-table"><div class="mc-dealer"><h3>Pozo total <span class="mc-chip"></span> ${g.pot}</h3><div class="cards">${[0,1,2,3,4].map(i=>g.community[i]?cardHTML(g.community[i]):'<div class="card slot">+</div>').join('')}</div></div><div class="mc-player-ring">${g.players.map((pl,i)=>`<div class="mc-player-pill ${i===g.turn&&!g.done?'active':''}"><b>${i===0?(p.avatar||'👤'):'👤'} ${esc(pl.name)}</b><div class="cards">${pl.cards.map(c=>cardHTML(c,true)).join('')}</div><small>${esc(pl.label || pl.eval?.name || (i===g.turn?'Turno':'En mesa'))}</small></div>`).join('')}</div></section>${renderLog(g.log)}<div class="mc-action-dock" style="grid-template-columns:repeat(4,1fr)">${g.done?`<button class="mc-btn primary" onclick="startHoldem()">Nueva</button><button class="mc-btn outline" onclick="navHome()">Salir</button>`:`<button class="mc-btn outline" onclick="holdemAction('fold')">Retirarse</button><button class="mc-btn outline" onclick="holdemAction('call')">Pasar</button><button class="mc-btn primary" onclick="holdemAction('press')">Subir +1</button><button class="mc-btn outline" onclick="holdemStreet()">Revelar</button>`}</div></main>`}catch(e){oldHoldem?.()}};
})();
