(function(){
  const PROFILE_KEY = 'mesacards_profile_v7';
  const AVATARS = ['🦊','🐺','🐯','🦁','🐼','🐵','🦅','🐙'];
  const FRIENDS = [['Sofi','👩‍🦰'],['Marco','🧢'],['Vale','👩'],['Nico','🧔']];
  const $ = s => document.querySelector(s);
  const esc = v => String(v||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const data = {
    bj:['🂡','21 Flash','Rondas rápidas contra la banca.','mc-card-blue'],
    holdem:['♠','Hold’em Social','Cartas comunitarias, presión y lectura.','mc-card-gold'],
    rummy:['🃏','Rummy Parejas','Roba, combina y toca cuando convenga.','mc-card-pink'],
    gem:['💎','Gem Clash','Gemas, contratos y decisiones rápidas.','mc-card-blue']
  };
  function profile(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY))||null}catch{return null}}
  function saveProfile(p){localStorage.setItem(PROFILE_KEY,JSON.stringify({...p,updatedAt:Date.now()}));syncPlayers(p)}
  function syncPlayers(p){try{if(typeof state==='undefined')return;const old=state.players||[];const guest=old.find(x=>x.name&&!['Tú','Moni','Jugador 1','Jugador 2',p.name].includes(x.name))?.name||'Invitado';state.players=[{name:p.name,chips:old[0]?.chips||40},{name:guest,chips:old[1]?.chips||40}];persist?.()}catch{}}
  function toast2(t){if(typeof toast==='function')return toast(t);alert(t)}
  function logo(){return `<div class="mc-logo"><span class="mc-logo-icon">♣</span><span>Mesa<mark>Cards</mark></span></div>`}
  function top(){const p=profile();return `<header class="mc-top">${logo()}<div class="mc-profile-mini"><button class="mc-avatar" onclick="openLuxuryProfile()">${esc(p?.avatar||'👤')}</button><div class="mc-balance"><span class="mc-chip"></span><span>12.450</span><span>＋</span></div></div></header>`}
  function bottom(active='inicio'){return `<nav class="mc-bottom"><button class="${active==='inicio'?'active':''}" onclick="navHome()">⌂<br>Inicio</button><button onclick="openLuxuryOnline&&openLuxuryOnline('friends')">👥<br>Amigos</button><button onclick="openLuxuryOnline&&openLuxuryOnline('rooms')">♣<br>Salas</button><button class="${active==='perfil'?'active':''}" onclick="openLuxuryProfile()">♙<br>Perfil</button></nav>`}
  function gcard(id){const g=data[id];return `<button class="mc-game-card ${g[3]}" onclick="mcStart('${id}')"><i>${g[0]}</i><b>${g[1]}</b><small>${g[2]}</small></button>`}
  window.mcStart=function(id){const p=profile();if(!p)return openLuxuryProfile(()=>window.mcStart(id));syncPlayers(p);startGame(id)};
  function renderLuxuryHome(){const p=profile();app.innerHTML=`<main class="mc-page">${top()}<section class="mc-hero"><div class="mc-chip-hero">♣</div><div class="mc-status"><span class="mc-dot"></span>324 jugadores online</div><h1 class="mc-title">Juega cartas<br>con tus <span>amigos</span></h1><p class="mc-subtitle">Cada uno desde su celular. En <b>tiempo real</b> o local, siempre con fichas virtuales.</p><div class="mc-actions"><button class="mc-btn primary" onclick="mcStart('bj')">▶ Jugar ahora</button><button class="mc-btn outline" onclick="openLuxuryOnline&&openLuxuryOnline('friends')">👥 Invitar amigos</button></div></section><div class="mc-tabs"><button class="mc-tab active" onclick="openLuxuryOnline&&openLuxuryOnline('rooms')">🌐 Online</button><button class="mc-tab" onclick="mcStart('bj')">📱 Local</button><button class="mc-tab" onclick="openLuxuryOnline&&openLuxuryOnline('rooms')">🚪 Salas</button></div><section class="mc-game-grid">${gcard('bj')}${gcard('holdem')}${gcard('rummy')}${gcard('gem')}</section><section class="mc-panel"><div class="mc-panel-head"><h2>Amigos conectados</h2><button class="mc-link" onclick="openLuxuryOnline&&openLuxuryOnline('friends')">Ver todos ›</button></div><div class="mc-friends">${FRIENDS.map(f=>`<button class="mc-friend" onclick="openLuxuryOnline&&openLuxuryOnline('friends')"><span class="mc-avatar">${f[1]}</span><span>${f[0]}</span></button>`).join('')}<button class="mc-friend" onclick="openLuxuryOnline&&openLuxuryOnline('friends')"><span class="mc-avatar">＋</span><span>Invitar</span></button></div></section>${bottom('inicio')}</main>`;if(p)syncPlayers(p)}
  function closeOverlay(){$('.mc-overlay')?.remove()}
  window.openLuxuryProfile=function(after){const cur=profile()||{name:'',avatar:'🦊'};document.body.insertAdjacentHTML('beforeend',`<div class="mc-overlay"><section class="mc-sheet"><button class="mc-close">×</button>${top()}<h1 class="mc-title" style="font-size:42px">${cur.name?'Personaliza tu ':'Crea tu '}<span>${cur.name?'personaje':'perfil'}</span></h1><p class="mc-subtitle">Cada jugador usa su propio celular para jugar.</p><div class="mc-form"><input class="mc-input" id="mcName" maxlength="18" placeholder="Nombre de jugador" value="${esc(cur.name||'')}"><input class="mc-input" placeholder="Correo (opcional)"><div class="mc-input" style="display:flex;align-items:center;justify-content:space-between">🌐 Idioma / Región <b>Español (Latam)⌄</b></div></div><div class="mc-character"><div><div class="big" id="mcBigAvatar">${esc(cur.avatar||'🦊')}</div><h2>Elige tu avatar</h2><p style="color:var(--mc-muted)">Crea tu identidad en la mesa.</p></div></div><div class="mc-avatar-grid">${AVATARS.map(a=>`<button class="mc-avatar-pick ${a===(cur.avatar||'🦊')?'active':''}" data-a="${a}">${a}</button>`).join('')}</div><div class="mc-panel"><b>Outfit</b><div class="mc-actions"><button class="mc-btn outline">Clásico Elite</button><button class="mc-btn">Urbano Luxe</button><button class="mc-btn">Noche VIP</button></div><p style="color:var(--mc-muted)">Acepto jugar solo con fichas virtuales. No hay dinero real involucrado.</p></div><div class="mc-actions"><button class="mc-btn primary" id="mcSaveProfile">▶ ${cur.name?'Guardar personaje':'Continuar'}</button><button class="mc-btn outline" id="mcCancelProfile">Ya tengo perfil</button></div></section></div>`);let selected=cur.avatar||'🦊';$('.mc-close').onclick=closeOverlay;$('#mcCancelProfile').onclick=closeOverlay;document.querySelectorAll('.mc-avatar-pick').forEach(b=>b.onclick=()=>{selected=b.dataset.a;document.querySelectorAll('.mc-avatar-pick').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#mcBigAvatar').textContent=selected});$('#mcSaveProfile').onclick=()=>{const name=$('#mcName').value.trim();if(name.length<3)return toast2('Escribe un nombre de al menos 3 letras');saveProfile({name,avatar:selected,code:cur.code||('MC'+Math.random().toString(36).slice(2,8).toUpperCase()),createdAt:cur.createdAt||Date.now()});closeOverlay();renderLuxuryHome();toast2('Perfil guardado');if(typeof after==='function')after()}};
  renderHome=renderLuxuryHome;
  window.addEventListener('load',()=>setTimeout(()=>{if(typeof render==='function'&&state?.screen==='home')render();if(!profile())setTimeout(()=>openLuxuryProfile(),500)},700));
})();
