(function(){
  const PROFILE_KEY='mesacards_profile_v7', DEVICE_KEY='mesacards_guest_device_v1';
  let db=null,me=null,poll=null;
  const $=s=>document.querySelector(s), esc=v=>String(v||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  function profile(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY))||{name:'Jugador',avatar:'🦊'}}catch{return{name:'Jugador',avatar:'🦊'}}}
  function did(){let id=localStorage.getItem(DEVICE_KEY);if(!id){id=crypto.randomUUID?crypto.randomUUID():'dev-'+Date.now();localStorage.setItem(DEVICE_KEY,id)}return id}
  function client(){if(db)return db;if(!window.supabase||!window.MESACARDS_SUPABASE)throw new Error('No cargó Supabase');db=window.supabase.createClient(window.MESACARDS_SUPABASE.url,window.MESACARDS_SUPABASE.key,{auth:{persistSession:false,autoRefreshToken:false}});return db}
  function err(e){return e?.message||e?.details||e?.code||String(e||'Error')}
  function toast2(t){if(typeof toast==='function')return toast(t);alert(t)}
  function stop(){if(poll){clearInterval(poll);poll=null}}
  function close(){stop();document.querySelector('.mc-overlay')?.remove()}
  function sheet(html){close();document.body.insertAdjacentHTML('beforeend',`<div class="mc-overlay"><section class="mc-sheet"><button class="mc-close">×</button>${html}</section></div>`);$('.mc-close').onclick=close}
  function top(){return `<header class="mc-top"><div class="mc-logo"><span class="mc-logo-icon">♣</span><span>Mesa<mark>Cards</mark></span></div><div class="mc-balance"><span class="mc-chip"></span>12.450<span>＋</span></div></header>`}
  function bottom(active='salas'){return `<nav class="mc-bottom"><button onclick="navHome()">⌂<br>Inicio</button><button class="${active==='amigos'?'active':''}" onclick="openLuxuryOnline('friends')">👥<br>Amigos</button><button class="${active==='salas'?'active':''}" onclick="openLuxuryOnline('rooms')">♣<br>Salas</button><button onclick="openLuxuryProfile&&openLuxuryProfile()">♙<br>Perfil</button></nav>`}
  async function prep(){const p=profile();const res=await client().from('guest_profiles').upsert({device_id:did(),display_name:(p.name||'Jugador').slice(0,18),avatar:p.avatar||'🦊',updated_at:new Date().toISOString()},{onConflict:'device_id'}).select('*').single();if(res.error)throw res.error;me=res.data;return me}
  window.openLuxuryOnline=async function(view='friends'){sheet(`${top()}<div class="mc-social-header"><span class="mc-avatar">⏳</span><div><h2>Conectando</h2><p>Preparando MesaCards Online...</p></div></div>`);try{await prep();hub(view)}catch(e){sheet(`${top()}<div class="mc-social-header"><span class="mc-avatar">⚠️</span><div><h2>No se pudo conectar</h2><p>${esc(err(e))}</p></div></div><button class="mc-btn primary" onclick="openLuxuryOnline('${view}')">Reintentar</button>`)}};
  window.openMesaSocial=()=>openLuxuryOnline('friends');
  function hub(view='friends'){sheet(`${top()}<div class="mc-social-header"><span class="mc-avatar">${esc(me.avatar)}</span><div><h2>${esc(me.display_name)}</h2><p>ID: <span class="mc-code">${esc(me.player_code)}</span></p></div><button class="mc-btn" id="copyId">Copiar</button></div><div class="mc-stat-grid"><div class="mc-stat"><b>${me.total_points||0}</b><span>Puntos</span></div><div class="mc-stat"><b>${me.wins||0}</b><span>Victorias</span></div><div class="mc-stat"><b>${me.current_streak||0}</b><span>Racha</span></div></div><div class="mc-tabs"><button class="mc-tab ${view!=='rooms'?'active':''}" id="fTab">👥 Amigos</button><button class="mc-tab ${view==='rooms'?'active':''}" id="rTab">♣ Salas</button><button class="mc-tab" id="sTab">↗ Compartir</button></div><div id="mcOnlineBody"></div>${bottom(view==='rooms'?'salas':'amigos')}`);$('#copyId').onclick=async()=>{await navigator.clipboard?.writeText(me.player_code);toast2('ID copiado')};$('#fTab').onclick=friends;$('#rTab').onclick=rooms;$('#sTab').onclick=shareProfile;view==='rooms'?rooms():friends()}
  function friends(){$('#mcOnlineBody').innerHTML=`<div class="mc-search"><input class="mc-input" id="findP" placeholder="Buscar por ID o nombre"><button class="mc-btn primary" id="findBtn">Buscar</button></div><div class="mc-panel"><div class="mc-panel-head"><h3>Solicitudes</h3><button class="mc-link" id="loadReq">Ver</button></div><div class="mc-list" id="friendList"><p style="color:var(--mc-muted)">Busca amigos, agrégalos y luego invítalos a salas.</p></div></div>`;$('#findBtn').onclick=searchP;$('#loadReq').onclick=requests}
  async function searchP(){const q=$('#findP').value.trim(),box=$('#friendList');if(q.length<2)return toast2('Escribe ID o nombre');box.innerHTML='<p>Buscando...</p>';let req=client().from('guest_profiles').select('device_id,player_code,display_name,avatar').limit(10);req=q.toUpperCase().startsWith('MC-')?req.ilike('player_code',q.toUpperCase()):req.ilike('display_name',`%${q}%`);const res=await req;if(res.error)return box.innerHTML=`<p>${esc(err(res.error))}</p>`;const data=(res.data||[]).filter(x=>x.device_id!==me.device_id);box.innerHTML=data.length?data.map(p=>`<div class="mc-row"><span class="mc-avatar">${esc(p.avatar)}</span><div class="grow"><b>${esc(p.display_name)}</b><br><small class="mc-code">${esc(p.player_code)}</small></div><button class="mc-btn primary" data-add="${p.device_id}">Agregar</button></div>`).join(''):'<p>No encontré jugadores.</p>';box.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add))}
  async function add(id){const res=await client().from('guest_friendships').insert({requester_device:me.device_id,receiver_device:id,status:'pending'});toast2(res.error?'Ya existe solicitud o amistad':'Solicitud enviada')}
  async function requests(){const box=$('#friendList');box.innerHTML='<p>Cargando...</p>';const res=await client().from('guest_friendships').select('id,guest_profiles!guest_friendships_requester_device_fkey(display_name,avatar,player_code)').eq('receiver_device',me.device_id).eq('status','pending').limit(20);if(res.error)return box.innerHTML=`<p>${esc(err(res.error))}</p>`;box.innerHTML=res.data?.length?res.data.map(r=>`<div class="mc-row"><span class="mc-avatar">${esc(r.guest_profiles?.avatar||'👤')}</span><div class="grow"><b>${esc(r.guest_profiles?.display_name||'Jugador')}</b><br><small>Quiere agregarte</small></div><button class="mc-btn primary" data-accept="${r.id}">Aceptar</button></div>`).join(''):'<p>No tienes solicitudes pendientes.</p>';box.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>accept(b.dataset.accept))}
  async function accept(id){const res=await client().from('guest_friendships').update({status:'accepted',updated_at:new Date().toISOString()}).eq('id',id);toast2(res.error?'No se pudo aceptar':'Solicitud aceptada');requests()}
  function shareProfile(){const url=`${location.origin}${location.pathname}?profile=${encodeURIComponent(me.player_code)}`;$('#mcOnlineBody').innerHTML=`<div class="mc-panel"><h3>Compartir perfil</h3><div class="mc-row"><span class="mc-avatar">▦</span><div class="grow"><b>Comparte tu perfil</b><br><small>${esc(url)}</small></div><button class="mc-btn primary" id="shareLink">Compartir</button></div></div>`;$('#shareLink').onclick=()=>share(url,'Agrégame en MesaCards')}
  function rooms(){$('#mcOnlineBody').innerHTML=`<div class="mc-actions"><button class="mc-btn primary" id="newRoom">Crear sala</button><button class="mc-btn outline" onclick="openLuxuryOnline('friends')">Invitar amigos</button></div><div class="mc-search"><input class="mc-input" id="roomInput" placeholder="Código de sala"><button class="mc-btn primary" id="joinRoom">Entrar</button></div><div class="mc-panel"><h3>Cómo funciona</h3><p style="color:var(--mc-muted)">Cada jugador instala MesaCards en su celular, entra con el código y juega desde su propia pantalla.</p></div>`;$('#newRoom').onclick=createRoom;$('#joinRoom').onclick=()=>joinRoom($('#roomInput').value.trim().toUpperCase())}
  async function createRoom(){const code=Math.random().toString(36).slice(2,7).toUpperCase();const res=await client().from('guest_rooms').insert({room_code:code,host_device:me.device_id,game_key:'bj',max_players:6,game_state:{phase:'lobby'}}).select('*').single();if(res.error)return toast2(err(res.error));await client().from('guest_room_players').insert({room_id:res.data.id,device_id:me.device_id,seat_number:1});room(res.data.id)}
  async function joinRoom(code){if(!code)return toast2('Escribe código de sala');const res=await client().from('guest_rooms').select('*').eq('room_code',code).maybeSingle();if(res.error||!res.data)return toast2('Sala no encontrada');await client().from('guest_room_players').upsert({room_id:res.data.id,device_id:me.device_id},{onConflict:'room_id,device_id'});room(res.data.id)}
  async function bundle(id){const room=(await client().from('guest_rooms').select('*').eq('id',id).single()).data;const players=(await client().from('guest_room_players').select('device_id,guest_profiles(display_name,avatar,player_code)').eq('room_id',id).order('joined_at')).data||[];return{room,players}}
  async function room(id){const b=await bundle(id);if(!b.room)return toast2('Sala no encontrada');const host=b.room.host_device===me.device_id,url=`${location.origin}${location.pathname}?room=${b.room.room_code}`;sheet(`${top()}<div class="mc-panel"><div style="display:flex;gap:18px;align-items:center"><span style="font-size:74px;filter:drop-shadow(0 0 22px var(--mc-blue))">🂡</span><div><h1 style="margin:0;font-size:36px">21 Flash <small style="color:var(--mc-muted)">· Sala privada</small></h1><p>Código de sala <span class="mc-code">${esc(b.room.room_code)}</span> · <span style="color:var(--mc-green)">● Online</span></p><p style="color:var(--mc-muted)">Cada quien juega desde su propio celular.</p></div></div></div><div class="mc-room-grid">${b.players.map(p=>`<div class="mc-seat ${p.device_id===b.room.host_device?'host':''}"><span class="mc-avatar">${esc(p.guest_profiles?.avatar||'👤')}</span><h3>${esc(p.guest_profiles?.display_name||'Jugador')}</h3><p style="color:var(--mc-green)">${p.device_id===b.room.host_device?'★ Anfitrión':'✓ Listo'}</p></div>`).join('')}<button class="mc-seat" id="inviteSeat"><span class="mc-avatar">＋</span><h3>Invitar</h3></button></div><div class="mc-actions"><button class="mc-btn outline" id="shareRoom">↗ Compartir sala</button>${host?'<button class="mc-btn primary" id="startRoom">▶ Empezar partida</button>':''}</div><section class="mc-panel"><h3>Ajustes de la partida</h3><div class="mc-activity"><p>Rondas: 10</p><p>Fichas iniciales: 5.000</p><p>Límite de tiempo: 30 seg</p></div></section>${bottom('salas')}`);$('#shareRoom').onclick=()=>share(url,'Únete a mi sala de MesaCards');$('#inviteSeat').onclick=()=>share(url,'Únete a mi sala de MesaCards');if($('#startRoom'))$('#startRoom').onclick=()=>toast2('La mesa online visual está lista. La siguiente mejora conecta turnos completos aquí.');poll=setInterval(()=>room(id),2800)}
  async function share(url,text){try{if(navigator.share)await navigator.share({title:'MesaCards',text,url});else{await navigator.clipboard?.writeText(url);toast2('Link copiado')}}catch{}}
  window.addEventListener('load',()=>{const rc=new URLSearchParams(location.search).get('room');if(rc)setTimeout(async()=>{try{await prep();await joinRoom(rc.toUpperCase())}catch{}},1500)})
})();
