(function(){
const KEY='mesacards_profile_v7',AV=['🦊','🐺','🐯','🦁','🐼','🐵','🦅','🐙'];
const $=s=>document.querySelector(s),esc=v=>String(v||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function p(){try{return JSON.parse(localStorage.getItem(KEY))||null}catch{return null}}
function img(v,c='mc-avatar'){return String(v||'').startsWith('data:image/')?`<span class="${c}"><img src="${v}" style="width:100%;height:100%;object-fit:cover;border-radius:inherit"></span>`:`<span class="${c}">${esc(v||'👤')}</span>`}
function save(x){localStorage.setItem(KEY,JSON.stringify({...x,updatedAt:Date.now()}));try{if(typeof state!=='undefined'){const old=state.players||[];state.players=[{name:x.name,chips:old[0]?.chips||40},{name:'Invitado',chips:old[1]?.chips||40}];persist?.()}}catch{}}
function toast2(t){typeof toast==='function'?toast(t):alert(t)}
function logo(){return `<div class="mc-logo"><span class="mc-logo-icon">♣</span><span>Mesa<mark>Cards</mark></span></div>`}
function top(){let x=p();return `<header class="mc-top">${logo()}<div class="mc-profile-mini"><button class="mc-avatar-btn" onclick="openLuxuryProfile()">${img(x?.avatar)}</button><div class="mc-balance"><span class="mc-chip"></span><span>12.450</span><span>＋</span></div></div></header>`}
function bottom(){return `<nav class="mc-bottom"><button class="active" onclick="navHome()">⌂<br>Inicio</button><button onclick="openLuxuryOnline&&openLuxuryOnline('friends')">👥<br>Amigos</button><button onclick="openLuxuryOnline&&openLuxuryOnline('rooms')">♣<br>Salas</button><button onclick="openLuxuryProfile()">♙<br>Perfil</button></nav>`}
const games={bj:['🂡','21 Flash','Rondas rápidas contra la banca.','mc-card-blue'],holdem:['♠','Hold’em Social','Cartas comunitarias, presión y lectura.','mc-card-gold'],rummy:['🃏','Rummy Parejas','Roba, combina y toca cuando convenga.','mc-card-pink'],gem:['💎','Gem Clash','Gemas, contratos y decisiones rápidas.','mc-card-blue']};
function card(id){let g=games[id];return `<button class="mc-game-card ${g[3]}" onclick="mcStart('${id}')"><i>${g[0]}</i><b>${g[1]}</b><small>${g[2]}</small></button>`}
window.mcStart=id=>{let x=p();if(!x)return openLuxuryProfile(()=>mcStart(id));try{state.players=[{name:x.name,chips:40},{name:'Invitado',chips:40}];persist?.()}catch{} startGame(id)};
function home(){app.innerHTML=`<main class="mc-page">${top()}<section class="mc-hero"><div class="mc-chip-hero">♣</div><div class="mc-status"><span class="mc-dot"></span>Jugadores online</div><h1 class="mc-title">Juega cartas<br>con tus <span>amigos</span></h1><p class="mc-subtitle">Cada uno desde su celular. En <b>tiempo real</b> o local, siempre con fichas virtuales.</p><div class="mc-actions"><button class="mc-btn primary" onclick="mcStart('bj')">▶ Jugar ahora</button><button class="mc-btn outline" onclick="openLuxuryOnline&&openLuxuryOnline('friends')">👥 Invitar amigos</button></div></section><div class="mc-tabs"><button class="mc-tab active" onclick="openLuxuryOnline&&openLuxuryOnline('rooms')">🌐 Online</button><button class="mc-tab" onclick="mcStart('bj')">📱 Local</button><button class="mc-tab" onclick="openLuxuryOnline&&openLuxuryOnline('rooms')">🚪 Salas</button></div><section class="mc-game-grid">${card('bj')}${card('holdem')}${card('rummy')}${card('gem')}</section>${bottom()}</main>`}
function close(){document.querySelector('.mc-overlay')?.remove()}
function css(){if($('#mcProfileClean'))return;document.head.insertAdjacentHTML('beforeend',`<style id="mcProfileClean">.mc-avatar-btn{border:0;background:transparent;padding:0}.mc-profile-sheet{max-height:88dvh;padding:22px}.mc-profile-title{font-size:42px!important;margin-bottom:10px}.mc-profile-sub{font-size:17px;color:#cbd5e1;margin:0 0 16px}.mc-photo-card{margin:16px 0;border-radius:26px;padding:18px;text-align:center;background:rgba(5,13,27,.7);box-shadow:inset 0 0 0 1px rgba(255,255,255,.12)}.mc-big-pic{width:132px;height:132px;border-radius:50%;margin:0 auto 12px;font-size:86px;display:grid;place-items:center;overflow:hidden;background:linear-gradient(150deg,#1c385b,#071426);box-shadow:0 0 0 3px rgba(255,209,102,.55),0 0 35px rgba(39,168,255,.22)}.mc-safe-note{color:#a9b5ca;font-size:15px;line-height:1.35}.mc-profile-actions{position:sticky;bottom:0;background:linear-gradient(180deg,transparent,rgba(4,10,20,.98) 30%);padding-top:12px}</style>`)}
function readFile(f){return new Promise(r=>{let fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(f)})}
window.openLuxuryProfile=function(after){css();let cur=p()||{name:'',avatar:'🦊'},sel=cur.avatar||'🦊';close();document.body.insertAdjacentHTML('beforeend',`<div class="mc-overlay"><section class="mc-sheet mc-profile-sheet"><button class="mc-close" id="pfClose">×</button>${logo()}<h1 class="mc-title mc-profile-title">${cur.name?'Editar':'Crea tu'} <span>perfil</span></h1><p class="mc-profile-sub">Elige tu nombre y una foto o avatar para jugar.</p><input class="mc-input" id="pfName" maxlength="18" placeholder="Nombre de jugador" value="${esc(cur.name||'')}"><div class="mc-photo-card"><div id="pfBig" class="mc-big-pic">${img(sel,'mc-big-pic')}</div><h2>Foto de perfil</h2><p class="mc-safe-note">Usa una foto de tu galería o un avatar.</p><input id="pfFile" type="file" accept="image/*" hidden><button class="mc-btn outline" id="pfPick">📷 Elegir foto</button></div><div class="mc-avatar-grid">${AV.map(a=>`<button class="mc-avatar-pick ${a===sel?'active':''}" data-a="${a}">${a}</button>`).join('')}</div><p class="mc-safe-note">Solo fichas virtuales. No hay dinero real involucrado.</p><div class="mc-actions mc-profile-actions"><button class="mc-btn primary" id="pfSave">▶ Continuar</button>${cur.name?'<button class="mc-btn outline" id="pfCancel">Cancelar</button>':''}</div></section></div>`);function set(v){sel=v;$('#pfBig').innerHTML=img(v,'mc-big-pic');document.querySelectorAll('.mc-avatar-pick').forEach(b=>b.classList.toggle('active',b.dataset.a===v))}$('#pfClose').onclick=close;$('#pfCancel')&&($('#pfCancel').onclick=close);$('#pfPick').onclick=()=>$('#pfFile').click();$('#pfFile').onchange=async e=>{let f=e.target.files?.[0];if(f){set(await readFile(f));toast2('Foto agregada')}};document.querySelectorAll('.mc-avatar-pick').forEach(b=>b.onclick=()=>set(b.dataset.a));$('#pfSave').onclick=()=>{let name=$('#pfName').value.trim();if(name.length<3)return toast2('Escribe un nombre de al menos 3 letras');save({name,avatar:sel,code:cur.code||('MC-'+Math.random().toString(36).slice(2,8).toUpperCase()),createdAt:cur.createdAt||Date.now()});close();home();toast2('Perfil guardado');if(typeof after==='function')setTimeout(after,50)}};
renderHome=home;window.addEventListener('load',()=>setTimeout(()=>{if(typeof render==='function'&&state?.screen==='home')render();if(!p())setTimeout(()=>openLuxuryProfile(),500)},700));
})();
