(function(){
  const KEY='mesacards_profile_v7';
  const AV=['🦊','🐺','🐯','🦁','🐼','🐵','🦅','🐙'];
  const $=s=>document.querySelector(s);
  const esc=v=>String(v||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  function prof(){try{return JSON.parse(localStorage.getItem(KEY))||null}catch{return null}}
  function isImg(v){return String(v||'').startsWith('data:image/')}
  function avatar(v,cls='mc-fix-avatar'){return isImg(v)?`<span class="${cls}"><img src="${v}"></span>`:`<span class="${cls}">${esc(v||'👤')}</span>`}
  function toast2(t){if(typeof toast==='function')toast(t);else alert(t)}
  function save(p){localStorage.setItem(KEY,JSON.stringify({...p,updatedAt:Date.now()}));try{if(typeof state!=='undefined'){const old=state.players||[];state.players=[{name:p.name,chips:old[0]?.chips||40},{name:old[1]?.name&&old[1].name!==p.name?old[1].name:'Invitado',chips:old[1]?.chips||40}];persist?.()}}catch{}}
  function close(){document.querySelector('.mc-overlay')?.remove()}
  function readPhoto(file){return new Promise(res=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const s=260,c=document.createElement('canvas'),x=c.getContext('2d');c.width=s;c.height=s;const k=Math.max(s/img.width,s/img.height),w=img.width*k,h=img.height*k;x.drawImage(img,(s-w)/2,(s-h)/2,w,h);res(c.toDataURL('image/jpeg',.82))};img.src=r.result};r.readAsDataURL(file)})}
  function styles(){if($('#profileFixCss'))return;document.head.insertAdjacentHTML('beforeend',`<style id="profileFixCss">.mc-profile-sheet{padding:22px!important;max-height:88dvh}.mc-profile-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px}.mc-profile-title{font-size:42px!important;margin-bottom:10px!important}.mc-profile-sub{font-size:17px;color:#cbd5e1;margin:0 0 16px}.mc-simple-form{display:grid;gap:12px}.mc-photo-card{margin:16px 0;border-radius:26px;padding:18px;text-align:center;background:radial-gradient(circle at 50% 0,rgba(39,168,255,.18),transparent 45%),rgba(5,13,27,.7);box-shadow:inset 0 0 0 1px rgba(255,255,255,.12)}.mc-fix-avatar,.mc-big-pic{display:grid;place-items:center;overflow:hidden}.mc-big-pic{width:132px;height:132px;margin:0 auto 12px;border-radius:50%;font-size:86px;background:linear-gradient(150deg,#1c385b,#071426);box-shadow:0 0 0 3px rgba(255,209,102,.55),0 0 35px rgba(39,168,255,.22)}.mc-big-pic img,.mc-fix-avatar img{width:100%;height:100%;object-fit:cover}.mc-fix-avatar{width:54px;height:54px;border-radius:50%;font-size:28px}.mc-avatar-pick{color:white}.mc-safe-note{color:#a9b5ca;font-size:15px;line-height:1.35;margin:10px 0 0}.mc-profile-actions{position:sticky;bottom:0;background:linear-gradient(180deg,transparent,rgba(4,10,20,.98) 30%);padding-top:12px}.mc-avatar-btn{border:0;background:transparent;padding:0}</style>`)}
  window.openLuxuryProfile=function(after){
    styles();
    const cur=prof()||{name:'',avatar:'🦊'};let selected=cur.avatar||'🦊';
    close();
    document.body.insertAdjacentHTML('beforeend',`<div class="mc-overlay"><section class="mc-sheet mc-profile-sheet"><button class="mc-close" id="pfClose" type="button">×</button><div class="mc-profile-head"><div class="mc-logo"><span class="mc-logo-icon">♣</span><span>Mesa<mark>Cards</mark></span></div><div class="mc-balance"><span class="mc-chip"></span><span>12.450</span></div></div><h1 class="mc-title mc-profile-title">${cur.name?'Editar':'Crea tu'} <span>perfil</span></h1><p class="mc-profile-sub">Elige tu nombre y una foto o avatar para jugar.</p><div class="mc-simple-form"><input class="mc-input" id="pfName" maxlength="18" placeholder="Nombre de jugador" value="${esc(cur.name||'')}"></div><div class="mc-photo-card"><div id="pfBig" class="mc-big-pic">${avatar(selected,'mc-big-pic')}</div><h2>Foto de perfil</h2><p class="mc-safe-note">Puedes usar una foto de tu galería o un avatar.</p><input id="pfFile" type="file" accept="image/*" hidden><button class="mc-btn outline" id="pfPick" type="button">📷 Elegir foto</button></div><div class="mc-avatar-grid">${AV.map(a=>`<button type="button" class="mc-avatar-pick ${a===selected?'active':''}" data-a="${a}">${a}</button>`).join('')}</div><p class="mc-safe-note">Solo fichas virtuales. No hay dinero real involucrado.</p><div class="mc-actions mc-profile-actions"><button class="mc-btn primary" id="pfSave" type="button">▶ Continuar</button>${cur.name?'<button class="mc-btn outline" id="pfCancel" type="button">Cancelar</button>':''}</div></section></div>`);
    function setA(v){selected=v;$('#pfBig').innerHTML=avatar(v,'mc-big-pic');document.querySelectorAll('.mc-avatar-pick').forEach(b=>b.classList.toggle('active',b.dataset.a===v))}
    $('#pfClose').onclick=close;$('#pfCancel')?.addEventListener('click',close);$('#pfPick').onclick=()=>$('#pfFile').click();
    $('#pfFile').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;setA(await readPhoto(f));toast2('Foto agregada')};
    document.querySelectorAll('.mc-avatar-pick').forEach(b=>b.onclick=()=>setA(b.dataset.a));
    $('#pfSave').onclick=()=>{const name=$('#pfName').value.trim();if(name.length<3)return toast2('Escribe un nombre de al menos 3 letras');save({name,avatar:selected,code:cur.code||('MC-'+Math.random().toString(36).slice(2,8).toUpperCase()),createdAt:cur.createdAt||Date.now()});close();if(typeof render==='function')render();toast2('Perfil guardado');if(typeof after==='function')setTimeout(after,50)};
  };
})();
