(function(){
  const PROFILE_KEYS = ['mesacards_profile_v7','mesacards_profile_v6','mesacards_profile_v5'];
  const DEVICE_KEY = 'mesacards_guest_device_v1';
  let db = null, me = null, roomTimer = null, activeRoom = null;
  const $ = s => document.querySelector(s);
  const esc = v => String(v || '').replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const roomCode = () => Math.random().toString(36).slice(2,7).toUpperCase();
  const ranks = ['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
  const suits = ['♠','♥','♦','♣'];
  function did(){ let id=localStorage.getItem(DEVICE_KEY); if(!id){ id=crypto.randomUUID?crypto.randomUUID():'dev-'+Date.now(); localStorage.setItem(DEVICE_KEY,id); } return id; }
  function localProfile(){ for(const k of PROFILE_KEYS){ try{ const p=JSON.parse(localStorage.getItem(k)); if(p?.name) return p; }catch{} } return {name:'Jugador',avatar:'🦊'}; }
  function err(e){ if(!e) return 'Error vacío'; if(typeof e==='string') return e; const parts=[e.message,e.details,e.hint,e.code,e.status,e.name].filter(Boolean); if(parts.length) return parts.join(' · '); try{return JSON.stringify(e)||String(e)}catch{return String(e)} }
  function client(){ if(db) return db; if(!window.supabase||!window.MESACARDS_SUPABASE) throw new Error('No cargó la conexión online'); db=window.supabase.createClient(window.MESACARDS_SUPABASE.url,window.MESACARDS_SUPABASE.key,{auth:{persistSession:false,autoRefreshToken:false}}); return db; }
  function toast(text){ let el=$('.toast'); if(!el){el=document.createElement('div'); el.className='toast'; document.body.appendChild(el)} el.textContent=text; el.classList.add('show'); clearTimeout(el._t); el._t=setTimeout(()=>el.classList.remove('show'),2300); }
  function stopPoll(){ if(roomTimer){ clearInterval(roomTimer); roomTimer=null; } }
  function close(){ stopPoll(); $('.socialOverlay')?.remove(); }
  function shell(html){ stopPoll(); $('.socialOverlay')?.remove(); const el=document.createElement('div'); el.className='socialOverlay'; el.innerHTML=`<section class="socialSheet"><button class="socialClose" id="socialClose" type="button">×</button>${html}</section>`; document.body.appendChild(el); $('#socialClose').onclick=close; }
  async function prepare(){ const p=localProfile(); const name=(p.name||'Jugador').trim().slice(0,18); const res=await client().from('guest_profiles').upsert({device_id:did(),display_name:name.length>=3?name:'Jugador',avatar:p.avatar||'🦊',updated_at:new Date().toISOString()},{onConflict:'device_id'}).select('*').single(); if(res.error) throw res.error; me=res.data; return me; }
  async function openOnline(){ shell(`<div class="socialTop"><div class="socialAvatar">⏳</div><div><h2>Conectando</h2><p>Preparando tu perfil online...</p></div></div>`); try{ await prepare(); renderHub(); }catch(e){ const text=err(e); shell(`<div class="socialTop"><div class="socialAvatar">⚠️</div><div><h2>No se pudo conectar</h2><p>Revisa que el parche guest online esté ejecutado en Supabase.</p></div></div><div class="socialActions"><button class="btn primary" id="retryOnline">Reintentar</button><button class="btn ghost" id="copyError">Copiar error</button></div><p class="socialNotice">${esc(text)}</p>`); $('#retryOnline').onclick=openOnline; $('#copyError').onclick=async()=>{await navigator.clipboard?.writeText(text); toast('Error copiado')}; } }
  function renderHub(){ const url=`${location.origin}${location.pathname}?profile=${encodeURIComponent(me.player_code)}`; shell(`<div class="socialTop"><div class="socialAvatar">${esc(me.avatar)}</div><div><h2>${esc(me.display_name)}</h2><p><span class="socialCode">${esc(me.player_code)}</span> · Perfil online</p></div></div><div class="socialGrid"><div class="socialStat"><b>${me.total_points||0}</b><span>Puntos</span></div><div class="socialStat"><b>${me.wins||0}</b><span>Victorias</span></div><div class="socialStat"><b>${me.current_streak||0}</b><span>Racha</span></div><div class="socialStat"><b>${me.games_played||0}</b><span>Partidas</span></div></div><div class="socialActions"><button class="btn primary" id="newRoom">Crear sala</button><button class="btn ghost" id="shareMe">Compartir perfil</button></div><div class="socialForm"><input id="joinCode" placeholder="Código de sala"><button class="btn primary" id="joinBtn">Entrar</button></div><div class="socialForm"><input id="findPlayer" placeholder="Buscar amigo por ID o nombre"><button class="btn ghost" id="findBtn">Buscar</button></div><div class="socialResults" id="socialResults"></div><div class="socialActions"><button class="btn ghost" id="requestsBtn">Solicitudes</button><button class="btn ghost" id="copyId">Copiar ID</button></div><div class="inviteBox" id="shareBox" hidden>${esc(url)}</div>`); $('#newRoom').onclick=createRoom; $('#shareMe').onclick=()=>share(url,`Agrégame en MesaCards: ${me.display_name}`); $('#joinBtn').onclick=()=>joinRoom($('#joinCode').value.trim().toUpperCase()); $('#findBtn').onclick=searchPlayer; $('#requestsBtn').onclick=listRequests; $('#copyId').onclick=async()=>{await navigator.clipboard?.writeText(me.player_code); toast('ID copiado')}; }
  async function share(url,text){ $('#shareBox')?.removeAttribute('hidden'); if($('#shareBox')) $('#shareBox').textContent=url; try{ if(navigator.share) await navigator.share({title:'MesaCards',text,url}); else{ await navigator.clipboard?.writeText(url); toast('Link copiado') } }catch{} }
  async function searchPlayer(){ const q=$('#findPlayer').value.trim(), box=$('#socialResults'); if(q.length<2) return toast('Escribe ID o nombre'); box.innerHTML='<p class="socialNotice">Buscando...</p>'; let req=client().from('guest_profiles').select('device_id,player_code,display_name,avatar,level,wins').limit(8); req=q.toUpperCase().startsWith('MC-')?req.ilike('player_code',q.toUpperCase()):req.ilike('display_name',`%${q}%`); const res=await req; if(res.error) return box.innerHTML=`<p class="socialNotice">${esc(err(res.error))}</p>`; const data=(res.data||[]).filter(p=>p.device_id!==me.device_id); if(!data.length) return box.innerHTML='<p class="socialNotice">No encontré jugadores.</p>'; box.innerHTML=data.map(p=>`<article class="socialResult"><span class="avatar">${esc(p.avatar||'🦊')}</span><div><b>${esc(p.display_name)}</b><small><span class="socialCode">${esc(p.player_code)}</span></small></div><button class="btn small primary" data-add="${p.device_id}">Agregar</button></article>`).join(''); box.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>sendRequest(b.dataset.add)); }
  async function sendRequest(id){ const res=await client().from('guest_friendships').insert({requester_device:me.device_id,receiver_device:id,status:'pending'}); toast(res.error?'Ya existe solicitud o amistad':'Solicitud enviada'); }
  async function listRequests(){ const box=$('#socialResults'); box.innerHTML='<p class="socialNotice">Cargando solicitudes...</p>'; const res=await client().from('guest_friendships').select('id,requester_device,status,guest_profiles!guest_friendships_requester_device_fkey(display_name,avatar,player_code)').eq('receiver_device',me.device_id).eq('status','pending').limit(20); if(res.error) return box.innerHTML=`<p class="socialNotice">${esc(err(res.error))}</p>`; if(!res.data.length) return box.innerHTML='<p class="socialNotice">No tienes solicitudes pendientes.</p>'; box.innerHTML=res.data.map(r=>`<article class="socialResult"><span class="avatar">${esc(r.guest_profiles?.avatar||'🦊')}</span><div><b>${esc(r.guest_profiles?.display_name||'Jugador')}</b><small>${esc(r.guest_profiles?.player_code||'')}</small></div><button class="btn small primary" data-accept="${r.id}">Aceptar</button></article>`).join(''); box.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>acceptRequest(b.dataset.accept)); }
  async function acceptRequest(id){ const res=await client().from('guest_friendships').update({status:'accepted',updated_at:new Date().toISOString()}).eq('id',id); if(res.error) return toast('No se pudo aceptar'); toast('Solicitud aceptada'); listRequests(); }
  async function createRoom(){ const res=await client().from('guest_rooms').insert({room_code:roomCode(),host_device:me.device_id,game_key:'bj',max_players:4,game_state:{phase:'lobby'}}).select('*').single(); if(res.error) return toast(err(res.error)); await client().from('guest_room_players').insert({room_id:res.data.id,device_id:me.device_id,seat_number:1}); showRoom(res.data.id); }
  async function joinRoom(codeText){ if(!codeText) return toast('Escribe código de sala'); const res=await client().from('guest_rooms').select('*').eq('room_code',codeText).maybeSingle(); if(res.error||!res.data) return toast('Sala no encontrada'); await client().from('guest_room_players').upsert({room_id:res.data.id,device_id:me.device_id},{onConflict:'room_id,device_id'}); showRoom(res.data.id); }
  async function roomData(roomId){ const room=(await client().from('guest_rooms').select('*').eq('id',roomId).single()).data; const players=(await client().from('guest_room_players').select('device_id,seat_number,guest_profiles(display_name,avatar,player_code)').eq('room_id',roomId).order('joined_at')).data||[]; return {room,players}; }
  async function showRoom(roomId){ activeRoom=roomId; const data=await roomData(roomId); const room=data.room; if(!room) return toast('Sala no encontrada'); if(room.status==='playing') return renderGame(room,data.players); const host=room.host_device===me.device_id; const url=`${location.origin}${location.pathname}?room=${encodeURIComponent(room.room_code)}`; shell(`<div class="socialTop"><div class="socialAvatar">🎮</div><div><h2>Sala ${esc(room.room_code)}</h2><p>21 Flash online · ${data.players.length}/${room.max_players} jugadores</p></div></div><div class="inviteBox">${esc(url)}</div><div class="socialResults">${data.players.map(p=>`<article class="socialResult"><span class="avatar">${esc(p.guest_profiles?.avatar||'🦊')}</span><div><b>${esc(p.guest_profiles?.display_name||'Jugador')}</b><small>${esc(p.guest_profiles?.player_code||'')}</small></div></article>`).join('')}</div><div class="socialActions"><button class="btn primary" id="shareRoom">Compartir sala</button>${host?'<button class="btn primary" id="startOnline">Empezar</button>':''}<button class="btn ghost" id="backHub">Perfil</button></div><p class="socialNotice">Cada persona entra desde su celular con este código. El juego se actualiza en línea.</p>`); $('#shareRoom').onclick=()=>share(url,'Únete a mi sala de MesaCards'); $('#backHub').onclick=renderHub; if(host) $('#startOnline').onclick=()=>startOnline(room,data.players); roomTimer=setInterval(()=>refreshRoom(roomId),1600); }
  async function refreshRoom(roomId){ if(!$('.socialOverlay')) return stopPoll(); const data=await roomData(roomId); if(!data.room) return; if(data.room.status==='playing') renderGame(data.room,data.players); }
  function deck(){ const a=[]; for(const s of suits) for(const r of ranks) a.push({r,s,red:s==='♥'||s==='♦'}); for(let i=a.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [a[i],a[j]]=[a[j],a[i]]; } return a; }
  function val(cards){ let t=0,a=0; for(const c of cards){ if(c.r==='A'){t+=11;a++} else t+=Math.min(10,Number(c.r)||10); } while(t>21&&a){t-=10;a--} return t; }
  async function startOnline(room,players){ if(players.length<2) return toast('Faltan jugadores'); const d=deck(); const hands=players.map(p=>({device_id:p.device_id,name:p.guest_profiles?.display_name||'Jugador',avatar:p.guest_profiles?.avatar||'🦊',cards:[d.shift(),d.shift()],done:false,result:'',chips:40})); const state={phase:'playing',deck:d,dealer:[d.shift(),d.shift()],turn:0,done:false,hands,log:['Partida online iniciada.']}; const res=await client().from('guest_rooms').update({status:'playing',game_state:state,updated_at:new Date().toISOString()}).eq('id',room.id); if(res.error) return toast(err(res.error)); renderGame({...room,status:'playing',game_state:state},players); }
  function card(c,hidden=false){ if(hidden||!c) return '<span class="card mini back">MC</span>'; return `<span class="card mini ${c.red?'red':'black'}"><b>${c.r}</b><span>${c.s}</span></span>`; }
  function renderGame(room,players){ stopPoll(); const g=room.game_state||{}; const meHand=(g.hands||[]).find(h=>h.device_id===me.device_id); const current=g.hands?.[g.turn]; const myTurn=current&&current.device_id===me.device_id&&!g.done&&!meHand?.done; shell(`<div class="socialTop"><div class="socialAvatar">🂡</div><div><h2>21 Flash Online</h2><p>Sala ${esc(room.room_code)} · ${myTurn?'Tu turno':'Esperando turno'}</p></div></div><section class="table"><h3>Banca virtual</h3><div class="cards">${(g.dealer||[]).map((c,i)=>card(c,!g.done&&i===1)).join('')}</div><p class="score">${g.done?val(g.dealer||[]):'?'}</p><div class="playersStrip">${(g.hands||[]).map((h,i)=>`<div class="playerSeat ${i===g.turn&&!g.done?'active':''}"><h4>${esc(h.avatar||'👤')} ${esc(h.name)}</h4><div class="cards smallCards">${h.cards.map(c=>card(c)).join('')}</div><p>${val(h.cards)} · ${esc(h.result|| (i===g.turn?'Turno':'Espera'))}</p></div>`).join('')}</div></section><div class="socialActions">${myTurn?'<button class="btn primary" id="hitBtn">Pedir carta</button><button class="btn ghost" id="standBtn">Plantarse</button>':''}<button class="btn ghost" id="roomBtn2">Sala</button></div><div class="socialResults">${(g.log||[]).slice(-5).reverse().map(x=>`<p class="socialNotice">${esc(x)}</p>`).join('')}</div>`); $('#roomBtn2').onclick=()=>showRoom(room.id); if(myTurn){ $('#hitBtn').onclick=()=>move(room,'hit'); $('#standBtn').onclick=()=>move(room,'stand'); } roomTimer=setInterval(()=>refreshGame(room.id),1400); }
  async function refreshGame(roomId){ if(!$('.socialOverlay')) return stopPoll(); const r=(await client().from('guest_rooms').select('*').eq('id',roomId).single()).data; if(r) renderGame(r,[]); }
  async function move(room,type){ const fresh=(await client().from('guest_rooms').select('*').eq('id',room.id).single()).data; const g=fresh.game_state; const h=g.hands[g.turn]; if(!h||h.device_id!==me.device_id||g.done) return; if(type==='hit'){ h.cards.push(g.deck.shift()); const score=val(h.cards); g.log.push(`${h.name} pidió carta.`); if(score>21){ h.done=true; h.result='Se pasó'; g.log.push(`${h.name} se pasó con ${score}.`); next(g); } } else { h.done=true; h.result='Plantado'; g.log.push(`${h.name} se plantó con ${val(h.cards)}.`); next(g); } await client().from('guest_rooms').update({game_state:g,updated_at:new Date().toISOString()}).eq('id',room.id); renderGame({...fresh,game_state:g},[]); }
  function next(g){ const n=g.hands.findIndex((h,i)=>i>g.turn&&!h.done); if(n>=0){g.turn=n;return} finish(g); }
  function finish(g){ while(val(g.dealer)<17) g.dealer.push(g.deck.shift()); const d=val(g.dealer); g.hands.forEach(h=>{ const hv=val(h.cards); let r='Empate'; if(hv>21) r='Pierde'; else if(d>21||hv>d) r='Gana'; else if(hv<d) r='Pierde'; h.result=r; g.log.push(`${h.name}: ${r}.`); }); g.done=true; }
  function addHomeButton(){ document.querySelectorAll('.socialFab').forEach(el=>el.remove()); const actions=document.querySelector('.hero .heroActions'); if(actions&&!$('#onlineBtn')) actions.insertAdjacentHTML('beforeend','<button class="btn ghost" id="onlineBtn" type="button">Online</button>'); $('#onlineBtn')?.addEventListener('click',openOnline); }
  async function handleDeepLink(){ const rc=new URLSearchParams(location.search).get('room'); if(rc){ try{ await prepare(); await joinRoom(rc.toUpperCase()); }catch{} } }
  window.openMesaSocial=openOnline; window.addEventListener('load',()=>{ setInterval(addHomeButton,1000); setTimeout(handleDeepLink,1200); });
})();
